#!/usr/bin/env python3
# pulputils
# Copyright (C) 2016  Salvo "LtWorf" Tomaselli
#
# pulputils is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# author Salvo "LtWorf" Tomaselli <tiposchi@tiscali.it>

import os
import sys


SUBSTITUTIONS = {
    (' ', '_'),
    ('!', ''),
    ('(', '['),
    (')', ']'),
    ('\'', ''),
    ('"', ''),
}


def fixedname(name, substitutions):
    '''
    Returns the new name, according to substitutions
    '''
    for a, b in substitutions:
        name = name.replace(a, b)
    return name


def rename_things(dirname, substitutions, verbose, ignoreerrors):
    try:
        files = os.listdir(dirname)
    except FileNotFoundError:
        print('File not found', file=sys.stderr)
        return 2
    except NotADirectoryError:
        print('Not a directory', file=sys.stderr)
        return 2

    for i in files:
        j = fixedname(i, substitutions)
        if i == j:
            continue # Nothing to do
        if not os.path.exists(dirname + '/' + j):
            if verbose:
                print('%s -> %s' % (i, j))
            os.rename(dirname + '/' + i, dirname + '/' + j)
        else:
            print('Skipping %s -> %s' % (i, j), file=sys.stderr)
            if not ignoreerrors:
                return 1
    return 0


def main():
    r = rename_things(sys.argv[1], SUBSTITUTIONS, False, False)
    sys.exit(r)


if __name__ == '__main__':
    main()
